version: '2.4'

services:
  message-analyzer:
    image: application/message-analyzer:simple
    depends_on:
      rabbit-mq:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
    ports:
      - 8092:8080

  medical-monitoring:
    image: application/medical-monitoring:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
    healthcheck:
      interval: 50s
      timeout: 10s
      retries: 2
    environment:
      SERVER_PORT: 8082
    ports:
      - 8093:8080

  person-service:
    image: application/person-service:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
      medical-monitoring:
        condition: service_healthy
    environment:
      SERVER_PORT: 8083
    ports:
      - 8091:8080

  rabbit-mq:
    image: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 50s
      timeout: 5s
      retries: 2

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ligadb
      POSTGRES_USER: ligauser
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"