version: '2.4'

services:
  message-analyzer:
    image: application/message-analyzer:simple
    environment:
      SERVER_PORT: 8081
    ports:
      - 8092:8080

  medical-monitoring:
    image: application/medical-monitoring:simple
    depends_on:
      message-analyzer:
        condition: service_started
    environment:
      SERVER_PORT: 8082
    ports:
      - 8093:8080

  person-service:
    image: application/person-service:simple
    depends_on:
      message-analyzer:
        condition: service_started
      medical-monitoring:
        condition: service_started
    environment:
      SERVER_PORT: 8083
    ports:
      - 8091:8080

  rabbit-mq:
    image: rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ligadb"
      POSTGRES_USER: "ligauser"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"